### ISSUE TITLE
Delay by cron

### ISSUE THREAD

**Issue by Raolibec** [MUDOTMY/moodle-availability_othercompleted#15]
While course1 is finished, the the course2 is not unlock immediately，user must wait  till the next completion run is finished then reflash.

**Comment by sam-suresh** [comment]
Isn't the cron should run every one minute? 

I believe Moodle badges also issued by cron. So other restrictions for example by badge also need to wait cron to complete.

**Comment by Tonychee** [comment]
Hi Suresh, could I get your assistance as to how to change the running time of the cron script? 

I have this message: The admin/cli/cron.php script has not been run for 59 mins 35 secs and should run every 1 min

But I am not sure how to change it. I have read this: https://docs.moodle.org/310/en/Cron, but it's quite confusing
