### ISSUE TITLE
"Available if other course is NOT completed" possible?

### ISSUE THREAD

**Issue by VOOM108** [MUDOTMY/moodle-availability_othercompleted#16]
The plugin only gives the option "course" "must be completed" but not "must not be completed". Thus I tried to revert the logic by adding it inside an availability-set with "following must not". The message shown looked promising: "You have incompleted course **course2** (hidden otherwise)" - but it does not work. 

(Moodle 3.5 with latest version of plugin)

**Comment by VOOM108** [comment]
In addition: actually what happens is: 
1. The other course is completed - the activity is shown whether the availability is enclosed with a "must not" or "must"
2. The other course is not completed - the acitivity is not shown whether the avail. is enclosed with a "must not" or "must"

So I presume that there is sth. in the logic of the plugin that enforces that...

**Comment by sam-suresh** [comment]
Adding on next update
