### ISSUE TITLE
Restriction doesn't go away

### ISSUE THREAD

**Issue by objt-je** [MUDOTMY/moodle-availability_othercompleted#17]
Hello, I let IT install the plugin and I have configured a restriction to start the module Assignment. First the course 'Planning' should be completed. But even after 20 minutes that the course was completed I can not enter the Assignment. Is there a long delay?

![image](https://user-images.githubusercontent.com/71714848/93896873-bd366d00-fcf1-11ea-9617-62cdf745e3fd.png)
![image](https://user-images.githubusercontent.com/71714848/93896934-cfb0a680-fcf1-11ea-9b65-e636d6f3dd27.png)

**Comment by jhernandezu01** [comment]
I have the same problem!

**Comment by amarizaty** [comment]
@objt-je @jhernandezu01 

can you check if your cron has been run to update status your course in report as complete.  

example image report your course set as complete.

![Screenshot 2021-03-30 at 7 30 49 AM](https://user-images.githubusercontent.com/49379422/112912330-e1a05580-9129-11eb-819d-773720fbc3f3.png)
