### ISSUE TITLE
Moodle 3.9 and 3.10

### ISSUE THREAD

**Issue by Tonychee** [MUDOTMY/moodle-availability_othercompleted#18]
Hi, my current moodle version is 3.9. Can't seem to be able to install the plugin into my site

**Comment by jhernandezu01** [comment]
i can install, but, the plugin doesn't work!

**Comment by rlgh770** [comment]
Hi using moodle 3.10 the restrictions are not being lifted

**Comment by Bambuspony** [comment]
Hi Sam Suresh, thank You for the work with this plugin. I wonder, if You will make it available for version 3.10?

**Comment by tonyyeb** [comment]
I have tested this on two different 3.10 sites and it works fine. Not sure what you are all doing but it works for me.

**Comment by Bambuspony** [comment]
Oh sorry, our update was not done properly. Yes, now it works fine on 3.10 - Thanks a lot for this plugin!

**Comment by VOOM108** [comment]
> Oh sorry, our update was not done properly. Yes, now it works fine on 3.10 - Thanks a lot for this plugin!

Could you tell, what was done wrong in your case? Because I have the plugin in a 3.9 after updating from 3.5 and it seemed to be fine, but the activities that should be shown with that restriction aren't any more.

**Comment by sam-suresh** [comment]
Updated to new version
