### ISSUE TITLE
Can't display restrict access

### ISSUE THREAD

**Issue by teawaterwu** [MUDOTMY/moodle-availability_othercompleted#20]
My moodle version was 3.2 and I had upgraded it to 3.8.9. I have installed availability_othercompleted_moodle38_2020051201 plugin in my server successfully,but I can't see any restrict access after confirmed this plugin enabled.
![image](https://user-images.githubusercontent.com/48787981/138638222-8a3359f8-d42d-4c89-8265-02549591ad10.png)
If I install a fully new moodle 3.8.9 and install plugin,it works.
Any suggestions should be appreciated!

**Comment by sam-suresh** [comment]
I afraid its not plugin issue. Pls try with other plugins if u face same issue. Also I released new version. Please try it out.
