### ISSUE TITLE
variables naming

### ISSUE THREAD

**Issue by ak4t0sh** [MUDOTMY/moodle-availability_othercompleted#3]
https://github.com/MUDOTMY/moodle-restriction-other-course-completion/blob/fe7f9c73413ec37f63a2930917329aa9f9c52131/classes/frontend.php#L56

your variable is named `$modinfo` but is not related to modules info at all it contains courses.
So `$courses` would be a more appropriated name.

**Comment by amarizaty** [comment]
5 Dec 2019 upodated.
