### ISSUE TITLE
Condition checking is wrong

### ISSUE THREAD

**Issue by kmp8072** [MUDOTMY/moodle-availability_othercompleted#6]
Hi, I installed this plugin on moodle version 3.3.9 and found that it takes not completed courses as complete while it is in progress only. I found that this plugin just checks for the entry of user for the course in course_completion table but it doesn't check the status which can be fixed by checking status as 50.

**Comment by sam-suresh** [comment]
Hi @kmp8072 
Im checking on this and will update the plugin over the weekend. Thanks

**Comment by amarizaty** [comment]
5 Dec 2019 updated.
