### ISSUE TITLE
Impossible to find course in large Moodle installs

### ISSUE THREAD

**Issue by jeffw87** [MUDOTMY/moodle-availability_othercompleted#7]
Slight issue for those of us with +1000 courses. Could the list be ordered alphabetically or we could type in the shortname, fullname, or ID of the course and it will autofill?

Let me know if you would like some help with the coding. I am working on just the sorting but autofill would be spectacular but much more complicated to implement.

**Comment by amarizaty** [comment]
25 Feb 2020
- list be ordered alphabetically

**Comment by sam-suresh** [comment]
Arranged alphabetical order.
